CONFIG = {
    'FACEBOOK_TOKEN': 'EAAE9pkz7ZBQQBAMgfFpZAtztDqzmUrzFbUxH9VmUF0wO3cKyMV5cGgImNIDq9XXzqJeAxJDG1WOZAVqqYk5pv0z5BXZCJnZCa6UGiZA09J9K5W1X5zE1IC6wpifj0W9cLxKN3BKeWS7dSlKyl2gpotg07OSWUQkza7OCPFZALrhnAZDZD',
    'VERIFY_TOKEN': 'verify_gbmbot',
    'SERVER_URL': 'https://gbm-but.herokuapp.com/'
}