CONFIG = {
    'FACEBOOK_TOKEN': 'EAAaYGKu6yNUBADqliFIZBIlm6xYjr6fw3V8KB0tESSestaEofr1d57ySV8EEcZB8dOvZCSDrBTdJxMbijkYYaiHK8P6NTjcFZAt5rDZCMfDMMTggKaO0IdIofyZCTTSZBceRVUjX40WicK0Iu0aEKMHIPXDh7x5GdeaAR9l0OtQGAZDZD',
    'VERIFY_TOKEN': 'verify_gbmbot',
    'SERVER_URL': 'https://gbm-but.herokuapp.com/'
}